class Autogenerated {
  List<Courses>? courses;
  int? length;

  Autogenerated({this.courses, this.length});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['courses'] != null) {
      List<Courses> courses = [Courses()];
      json['courses'].forEach((v) {
        courses.add(new Courses.fromJson(v));
      });
    }
    length = json['length'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.courses != null) {
      data['courses'] = this.courses!.map((v) => v.toJson()).toList();
    }
    data['length'] = this.length;
    return data;
  }
}

class Courses {
  String? sId;
  List? users = [];
  int? rating;
  List? reviews= [];
  String? name;
  String? thumbnail;
  String? shortDescription;
  Price? price;
  String? prerequisite;
  String? description;
  List<CourseMaterial>? courseMaterial = [];
  String? teaserVideo;
  String? category;
  String? teacher;
  String? createdAt;
  String? updatedAt;
  int? iV;

  Courses(
      {this.sId,
        this.users,
        this.rating,
        this.reviews,
        this.name,
        this.thumbnail,
        this.shortDescription,
        this.price,
        this.prerequisite,
        this.description,
        this.courseMaterial,
        this.teaserVideo,
        this.category,
        this.teacher,
        this.createdAt,
        this.updatedAt,
        this.iV});

  Courses.fromJson(Map<String, dynamic> json) {
    sId = json['_id'];
    if (json['users'] != null) {
      users = json['users'];
    }
    rating = json['rating'];
    if (json['reviews'] != null) {
      reviews = json['reviews'];
    }
    name = json['name'];
    thumbnail = json['thumbnail'];
    shortDescription = json['shortDescription'];
    price = json['price'] != null ? new Price.fromJson(json['price']) : null;
    prerequisite = json['prerequisite'];
    description = json['description'];
    if (json['courseMaterial'] != null) {
      courseMaterial = [CourseMaterial()];
      json['courseMaterial'].forEach((v) {
        courseMaterial!.add(new CourseMaterial.fromJson(v));
      });
    }
    teaserVideo = json['teaserVideo'];
    category = json['category'];
    teacher = json['teacher'];
    createdAt = json['createdAt'];
    updatedAt = json['updatedAt'];
    iV = json['__v'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['_id'] = this.sId;
    if (this.users != null) {
      data['users'] = this.users!.map((v) => v.toJson()).toList();
    }
    data['rating'] = this.rating;
    if (this.reviews != null) {
      data['reviews'] = this.reviews!.map((v) => v.toJson()).toList();
    }
    data['name'] = this.name;
    data['thumbnail'] = this.thumbnail;
    data['shortDescription'] = this.shortDescription;
    if (this.price != null) {
      data['price'] = this.price!.toJson();
    }
    data['prerequisite'] = this.prerequisite;
    data['description'] = this.description;
    if (this.courseMaterial != null) {
      data['courseMaterial'] =
          this.courseMaterial!.map((v) => v.toJson()).toList();
    }
    data['teaserVideo'] = this.teaserVideo;
    data['category'] = this.category;
    data['teacher'] = this.teacher;
    data['createdAt'] = this.createdAt;
    data['updatedAt'] = this.updatedAt;
    data['__v'] = this.iV;
    return data;
  }
}

class Price {
  String? currency;
  int? discount;
  String? sId;
  int? value;

  Price({this.currency, this.discount, this.sId, this.value});

  Price.fromJson(Map<String, dynamic> json) {
    currency = json['currency'];
    discount = json['discount'];
    sId = json['_id'];
    value = json['value'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['currency'] = this.currency;
    data['discount'] = this.discount;
    data['_id'] = this.sId;
    data['value'] = this.value;
    return data;
  }
}

class CourseMaterial {
  String? sId;
  String? name;
  List<Lectures>? lectures = [];

  CourseMaterial({this.sId, this.name, this.lectures});

  CourseMaterial.fromJson(Map<String, dynamic> json) {
    sId = json['_id'];
    name = json['name'];
    if (json['lectures'] != null) {
      lectures = [Lectures()];
      json['lectures'].forEach((v) {
        lectures!.add(new Lectures.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['_id'] = this.sId;
    data['name'] = this.name;
    if (this.lectures != null) {
      data['lectures'] = this.lectures!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Lectures {
  String? sId;
  String? title;
  String? description;
  String? thumbnail;
  String? videoUrl;

  Lectures(
      {this.sId, this.title, this.description, this.thumbnail, this.videoUrl});

  Lectures.fromJson(Map<String, dynamic> json) {
    sId = json['_id'];
    title = json['title'];
    description = json['description'];
    thumbnail = json['thumbnail'];
    videoUrl = json['videoUrl'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['_id'] = this.sId;
    data['title'] = this.title;
    data['description'] = this.description;
    data['thumbnail'] = this.thumbnail;
    data['videoUrl'] = this.videoUrl;
    return data;
  }
}
